"""Deleted locale from user model

Revision ID: 83692652ffa5
Revises: 318b32e653fa
Create Date: 2025-07-14 17:08:44.793549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83692652ffa5'
down_revision = '318b32e653fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('locale')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('locale', sa.VARCHAR(length=10), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
