"""Recreate ad332a282a54 changes

Revision ID: 9691d4d04438
Revises: 8ed1f8f799f5
Create Date: 2025-08-07 15:52:10.000429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9691d4d04438'
down_revision = '8ed1f8f799f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_notifications', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_notifications_product_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_notifications_product_id_fkey'), 'products', ['product_id'], ['id'])

    # ### end Alembic commands ###
