"""Add product_identifier to Product model

Revision ID: ad609dc92f65
Revises: d35eaec43e04
Create Date: 2025-08-16 23:06:22.828906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad609dc92f65'
down_revision = 'd35eaec43e04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_identifier', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_products_product_identifier'), ['product_identifier'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_product_identifier'))
        batch_op.drop_column('product_identifier')

    # ### end Alembic commands ###
