"""Add is_comparison_only flag to Product

Revision ID: b93405bf6d9e
Revises: ad609dc92f65
Create Date: 2025-08-17 13:45:03.707640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b93405bf6d9e'
down_revision = 'ad609dc92f65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_comparison_only', sa.Boolean(), nullable=True))

    op.execute("UPDATE products SET is_comparison_only = False")

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('is_comparison_only', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('is_comparison_only')

    # ### end Alembic commands ###
