"""Add telegram_state and temp_data to User model

Revision ID: cf7b4bd32dfe
Revises: 918acc50b7e2
Create Date: 2025-07-07 19:38:37.110355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf7b4bd32dfe'
down_revision = '918acc50b7e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_state', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('temp_data', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('temp_data')
        batch_op.drop_column('telegram_state')

    # ### end Alembic commands ###
