"""Add comparison_group_id to Product

Revision ID: d35eaec43e04
Revises: 9691d4d04438
Create Date: 2025-08-16 19:58:07.871820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd35eaec43e04'
down_revision = '9691d4d04438'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comparison_group_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_products_comparison_group_id'), ['comparison_group_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_comparison_group_id'))
        batch_op.drop_column('comparison_group_id')

    # ### end Alembic commands ###
